;;; logstash-conf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from logstash-conf.el

(autoload 'logstash-conf-mode "logstash-conf"
"Major mode for editing logstash configuration files.

\\{logstash-conf-mode-map\\}

In addition to any hooks its parent mode `prog-mode' might have run,
this mode runs the hook `logstash-conf-mode-hook', as the final or
penultimate step during initialization." t)
(add-to-list 'auto-mode-alist '("\\.logstash\\'" . logstash-conf-mode))
(add-to-list 'interpreter-mode-alist '("logstash" . logstash-conf-mode))
(register-definition-prefixes "logstash-conf" '("logstash-"))

;;; End of scraped data

(provide 'logstash-conf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; logstash-conf-autoloads.el ends here
